### ISSUE TITLE
Inconsistent opcodes count in local tournaments

### ISSUE THREAD

**Issue by remarkablerocket** [inglesp/botany#48]
When I play a single game between the attached bots, my bot (error_unable_to_connect4) always hits the opcode limit. In a tournament my bot only fails some of the time, even though the moves are identical.

Steps to reproduce:
Download and extract the bots from [bots.zip](https://github.com/inglesp/botany/files/2414102/bots.zip) and run the following games
```
$ botany play error_unable_to_connect.py loser.py
$ botany tournament error_unable_to_connect.py loser.py
```

I've used the state variable to track the highest number of opcodes used by my bot in any turn. You can get the botany client to report this info by adding one line to botany_core/runner.py, at the end of the `run_game` function:
```
         winner = game.check_winner(board)
         if winner is not None:
+            print("Winning bot's state:", state)
             assert winner == token
             return build_result(ResultType.COMPLETE, winning_scores[player_ix])
```

The opcode count appears to spike the first time the bot plays first and second, but it settles down to 20761 for the final 4 games of the 10. Given both bots follow predictable algorithms (neither use random) I'd expect the opcodes to be completely consistent?

**Comment by inglesp** [comment]
What you're seeing is caused by the `re` module doing some caching.  Specifically, whenever you call something like `re.search(pattern, string)`, it has to compile `pattern` into a [regular expression object](https://docs.python.org/3/library/re.html#re-objects).  This is a relatively expensive operation so it caches the resulting object, meaning that the compilation only has to happen once per pattern.

In `error_unable_to_connect4.py` (am still chuckling about that name), you have a lot of patterns which need to be compiled.  In a single game, the opcode limit is exceeded before they are all compiled.  However, the compiled patterns are cached, so after a few games all the patterns are compiled.

You can see this happening with the `--full-output` flag to the `tournament` command:

```
$ botany tournament error_unable_to_connect4.py loser.py --full-output
error_unable_to_connect4.py vs loser.py
  0 bot2 wins   bot1 exceeded the opcode limit
  1 bot2 wins   bot1 exceeded the opcode limit
  2 bot2 wins   bot1 exceeded the opcode limit
  3 bot1 wins  302030461
  4 bot1 wins  302030461

loser.py vs error_unable_to_connect4.py
  0 bot2 wins  0302036461
  1 bot2 wins  0302036461
  2 bot2 wins  0302036461
  3 bot2 wins  0302036461
  4 bot2 wins  0302036461


            Bot             | P  | W  | D  | L  | Score
----------------------------+----+----+----+----+------
error_unable_to_connect4.py | 10 |  7 |  0 |  3 |  4
loser.py                    | 10 |  3 |  0 |  7 | -4
```

Although this is an edge case it's potentially quite confusing, so I'll add a call to `re.purge()` at the top of `run_game`.

I bet @mjpieters would know if there are other similar internal caches that might cause the same problem.

**Comment by mjpieters** [comment]
> I bet @mjpieters would know if there are other similar internal caches that might cause the same problem.

Too many to name them all. :-) Python is full of cache-on-first-use paths that could spike your initial opcode use but then never show up again. Fun fact: for a few point releases of Python 3.2 and Python 3.3 a different caching strategy was used that [had a significant performance downside](https://stackoverflow.com/questions/14756790/why-are-uncompiled-repeatedly-used-regexes-so-much-slower-in-python-3). But the current implementation uses the cheap dictionary-with-a-ceiling approach again.

Still, you'd want to pre-compile your regexes beforehand and keep the cost of doing so out of your `get_next_move()` function. I used the following strategy to do so in my bot:

```python
def setup() -> None:
    global name1, name2, ...

    name1 = ...
    # etc.

def antigravity(cheating_bastard: None = setup()) -> None:
    # I'm totally weightless
    pass
```

to bypass the 'no top-level statements other than functions and imports' limitation. You can use that to compile your regular expressions too; use `name = re.compile(r'...')` then [use methods on the regex object](https://docs.python.org/3/library/re.html#regular-expression-objects) rather than the top-level functions.

**Comment by remarkablerocket** [comment]
Thanks both. I knew there'd be some clever way to reduce the cost of all those regexes, but this has mostly gone over my head. Time to do some reading I think...
